global:
  ensembl_ftp: ftp://ftp.ensembl.org/pub/
  release: 100
  features:
    regulatory_feature:
      columns:
        - feature_type_description
        - bound_seq_region_start
        - feature_type_name
        - bound_seq_region_end
        - so_name
        - so_accession
        - seq_region_name
        - stable_id
        - regulatory_feature_id
        - seq_region_start
        - seq_region_end
        - seq_region_strand
    motif_feature:
      columns:
        - score
        - seq_region_name
        - binding_matrix_id
        - seq_region_end
        - feature_type_name
        - motif_feature_id
        - display_label
        - seq_region_start
        - seq_region_strand
    mirna_target_feature:
      columns:
        - display_label
        - feature_type_class
        - seq_region_end
        - accession
        - evidence
        - so_name
        - seq_region_start
        - so_accession
        - mirna_target_feature_id
        - gene_stable_id
        - seq_region_name
        - seq_region_strand
        - feature_type_description
    external_feature:
      columns:
        - so_name
        - feature_type_class
        - so_accession
        - seq_region_strand
        - seq_region_start
        - display_label
        - seq_region_end
        - fs_display_label
        - external_feature_id
        - feature_type_description
        - seq_region_name
organisms:
  mus_musculus:
    fasta_file: Mus_musculus.GRCm38.dna_rm.toplevel.fa.gz
    2bit_file_name: mm10
    features:
      regulatory_feature:
        file: mmusculus_regulatory_feature__regulatory_feature__main.txt.gz
      motif_feature:
        file: mmusculus_motif_feature__motif_feature__main.txt.gz
      mirna_target_feature:
        file: mmusculus_mirna_target_feature__mirna_target_feature__main.txt.gz
      external_feature:
        file: mmusculus_external_feature__external_feature__main.txt.gz
  homo_sapiens:
    fasta_file: Homo_sapiens.GRCh38.dna.toplevel.fa.gz
    2bit_file_name: hg38
    features:
      regulatory_feature:
        file: hsapiens_regulatory_feature__regulatory_feature__main.txt.gz
      motif_feature:
        file: hsapiens_motif_feature__motif_feature__main.txt.gz
      mirna_target_feature:
        file: hsapiens_mirna_target_feature__mirna_target_feature__main.txt.gz
      external_feature:
        file: hsapiens_external_feature__external_feature__main.txt.gz